apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scriptcat-list-frontend.fullname" . }}
  labels:
    {{- include "scriptcat-list-frontend.labels" . | nindent 4 }}
type: Opaque
data:
  config: {{ .Values.config.config }}
  dbConfig: {{ .Values.config.dbConfig }}
