apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "scriptcat-list-frontend.fullname" . }}-sessions-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 20Gi
